---
title: "Homework 3"
output: html_document
---
```{r loadpackages, results = FALSE, message=FALSE}
library('tidyverse')
library('lme4')
library('factoextra')

```

# 1. Using Github

The repository can be accessed at https://ct18173.github.io/homework3/.

# 2. Stroop, Standing Up or Sitting Down

```{r loadingdata, results='hide'}

# Loading in the Stroop data.
stroopdata <- read.csv('stroop_standing_data.csv')

```

```{r datacleaning}
# I am cleaning the data by first removing the mistrials and then removing the practice phase trials. I am choosing to do this as the mistrial data will be incorrect and the practice trials are there to allow the participant to understand the task before the real trials begin.
stroopdataclean <- stroopdata %>% 
  filter(correct != 999) %>% 
  filter(phase != 'practice') %>%
  filter(congruency != 'baseline')
  
widestroopdata <- pivot_wider(stroopdataclean, names_from = phase, values_from = rt)

mean(stroopdataclean[stroopdataclean$congruency == 'congruent', 'rt']) #find out how to get mean

```

```{r fitmodel}
 #not working yet

```

# 3. The Dimensions of Popular Music

```{r loadingmusicdata, results='hide'}

# Loading in the Stroop data.
spotifydata <- read.csv('spotify_cleaned.csv')

```

```{r PCA}

pcaspotifydata <- select(spotifydata, -X, -Track.Name, -Artist, -Streams, -time_signature)
pcaspotifydata2 <- prcomp(pcaspotifydata)
summary(pcaspotifydata2)

factoextra::fviz_eig(pcaspotifydata2)
